// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBHsX-5YzkyQ9DBNJgpTfL8tZUdl4Q0C4',
    appId: '1:884058304379:android:5d20ae6b33e82716ce97de',
    messagingSenderId: '884058304379',
    projectId: 'spoken-odesey',
    storageBucket: 'spoken-odesey.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOOwB2Prrr34u6RqDpUUwMKz50eXZcJ0',
    appId: '1:884058304379:ios:2f262781a5d51f75ce97de',
    messagingSenderId: '884058304379',
    projectId: 'spoken-odesey',
    storageBucket: 'spoken-odesey.firebasestorage.app',
    androidClientId: '884058304379-cl69k71p3i8dp7pnm40d0fgv27jvt9b5.apps.googleusercontent.com',
    iosClientId: '884058304379-t5jeu8j0sjk4ptv43q5fbk7lid58pii0.apps.googleusercontent.com',
    iosBundleId: 'com.spokenodyssey.app',
  );
}
